### PR TITLE
fix message markers

### PR DESCRIPTION
**Pull request by andkem**
Fix encoding errors in marker handling code.

### CODE REVIEW

**Comment by freshprince** [comment]
hey @andkem

thanks for your pull request. would you mind providing some more information like what problem this actually fixes and how to trigger this problem?

**Comment by andkem** [comment]
> hey @andkem
> 
> thanks for your pull request. would you mind providing some more information like what problem this actually fixes and how to trigger this problem?

Sure. Do you want me to put more info in the commit message or here in the discussion?

**Comment by freshprince** [comment]
Either way is fine. I'd like to reproduce the problem.

**Comment by andkem** [comment]
I added a more thorough description in the commit message.

**Comment by freshprince** [comment]
Thanks! I committed a slightly modified version of your commit. Hope that's alright.

**Comment by andkem** [comment]
That's fine, thank you!

**Pull request closed without merging**
